// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetArcheAgeStatus():Promise<boolean>;

export function OpenExplorer():Promise<void>;

export function PickFolder():Promise<main.FolderStatus>;

export function SetFolder(arg1:string):Promise<main.FolderStatus>;
