// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetArcheAgeStatus() {
  return window['go']['main']['App']['GetArcheAgeStatus']();
}

export function OpenExplorer() {
  return window['go']['main']['App']['OpenExplorer']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function SetFolder(arg1) {
  return window['go']['main']['App']['SetFolder'](arg1);
}
